### ISSUE TITLE
Plan Wizard is not updating 'namespaces' if we skip and then come back to select

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#327] opened 2019-07-11 16:28 UTC
I ran into the below when I did:
1. In Plan Wizard, advance without selecting a namespace
2. Go back, in same wizard modal session, press back button
3. Select namespace
4. Advance as normal

It looks like the 'namespaces' field is not being updated on MigPlan.

<img width="1540" alt="Screen Shot 2019-07-11 at 12 23 37 PM" src="https://user-images.githubusercontent.com/206875/61068054-0cd39600-a3d7-11e9-9258-af6753d99637.png">

```
$ oc get migplan jwm0711c -o yaml
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  annotations:
    touch: a7caae13-3568-4f24-96fb-86f36201dac1
  creationTimestamp: "2019-07-11T16:17:12Z"
  generation: 2
  name: jwm0711c
  namespace: mig
  resourceVersion: "443934"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migplans/jwm0711c
  uid: 56e47e5c-a3f7-11e9-a1b2-063ca044fe88
spec:
  destMigClusterRef:
    name: host
    namespace: mig
  migStorageRef:
    name: my-s2-bucket
    namespace: mig
  srcMigClusterRef:
    name: ocp3
    namespace: mig
status:
  conditions:
  - category: Critical
    lastTransitionTime: "2019-07-11T16:17:12Z"
    message: The `migStorageRef` must reference a `migstorage`.
    reason: NotFound
    status: "True"
    type: InvalidStorageRef
  - category: Critical
    lastTransitionTime: "2019-07-11T16:17:12Z"
    message: The `namespaces` list may not be empty.
    status: "True"
    type: NamespaceListEmpty
```

**Comment by ibolton336** [comment] 2019-07-25 19:21
@jwmatthews I think this is occurring due to the issue @Danil-Grigorev pointed out here #372. 

Since the migplan is created on the step after the namespaces are selected during the PV discovery phase, the migplan will reflect what was selected there until the final wizard submit at the end of the wizard. @eriknelson Do you think we should just disable the back button functionality in the wizard? There could be some potential headaches involving plan object cleanup if we decide to allow the user to go back and change the namespaces & add a new plan.

**Comment by eriknelson** [comment] 2019-07-26 08:43
This wizard is going to require some thought because of the way we have to create objects in the middle of it; it's not just transient state like a normal wizard. I'm not really in favor of disabling the back button, because we're going to have to handle plan edits as well, so this problem isn't going to go away. I think we need to clearly define the expected behavior and plan how we can accomplish that given the current code state.

**Comment by eriknelson** [comment] 2019-07-31 15:24
Closing this since it's not possible to progress without any namespaces currently.

The more interesting issue here is being able to back up and select different namespaces. This needs to be covered by the plan edit work. We have a card that captures edit (https://github.com/fusor/mig-ui/issues/311), so I'll describe the issue there.

**Closed by eriknelson** 2019-07-31 15:25 UTC
Labels: beta-blocker, bug, low-hanging-fruit
