### ISSUE TITLE
Number of PVs is 0 instead of 1 when looking at a row of a MigPlan

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#394] opened 2019-07-30 02:42 UTC
In the shown MigPlan there was 1 PV that has been successfully stage/migrated.
The row is display 0 PVs yet there was 1 present in the MigPlan

<img width="1560" alt="Screen Shot 2019-07-29 at 10 41 06 PM" src="https://user-images.githubusercontent.com/206875/62096575-1ae83a00-b252-11e9-9b62-850e7ef70e80.png">

**Comment by Danil-Grigorev** [comment] 2019-07-30 17:02
@jwmatthews Migplan usually updates the list of PVs with remote watches, so after the migration the number usually change to 0. At the moment the icon is disconnected, but adding logic there won't ensure that the number won't change later. Also the Migmigration resource does not contain any information about the number of PVs moved or copied. Does this all mean the UI should gather the info from the referenced clusters, or this task should be left on migcontroller?

**Comment by jwmatthews** [comment] 2019-08-04 15:27
Reopening as issue is not yet fixed.
The issue is improved, when I created the plan it displayed the correct number of PVs, yet after it completed the migration it displayed 0 PVs.  If I scale the replicas back to running then MigPlan is updated and UI displays volume count as expected

This lines up to @Danil-Grigorev's previous comment https://github.com/fusor/mig-ui/issues/394#issuecomment-516506636

We need to think through how we want to fix this and where the data comes from, may involve changes to CR.



<img width="1598" alt="Screen Shot 2019-08-04 at 11 16 08 AM" src="https://user-images.githubusercontent.com/206875/62425610-69aa2f80-b6a9-11e9-8f41-d522ba51453a.png">


Look at the MigPlan after Migration has completed.

```
$ oc get migplan mediawiki01 -o yaml -n mig
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  annotations:
    touch: 26eb7914-8968-45a2-9f0e-8e150f69c085
  creationTimestamp: "2019-08-04T15:01:53Z"
  generation: 11
  name: mediawiki01
  namespace: mig
  resourceVersion: "2049671"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migplans/mediawiki01
  uid: cb77fd08-b6c8-11e9-8be2-0214de412234
spec:
  destMigClusterRef:
    name: host
    namespace: mig
  migStorageRef:
    name: jwms3
    namespace: mig
  namespaces:
  - mediawiki
  srcMigClusterRef:
    name: jwm0729ocp3a
    namespace: mig
status:
  conditions:
  - category: Required
    lastTransitionTime: "2019-08-04T15:02:06Z"
    message: The `persistentVolumes` list has been updated with discovered PVs.
    reason: Done
    status: "True"
    type: PvsDiscovered
  - category: Required
    lastTransitionTime: "2019-08-04T15:02:06Z"
    message: The storage resources have been created.
    status: "True"
    type: StorageEnsured
  - category: Required
    lastTransitionTime: "2019-08-04T15:02:07Z"
    message: The migration registry resources have been created.
    status: "True"
    type: RegistriesEnsured
  - category: Required
    lastTransitionTime: "2019-08-04T15:02:07Z"
    message: The migration plan is ready.
    status: "True"
    type: Ready

```


Then I scaled the replicas back on the source cluster, this is after a successful migration

```
$ oc scale  deploymentconfig mariadb --replicas=1 -n mediawiki
deploymentconfig.apps.openshift.io/mariadb scaled
$ oc scale  deploymentconfig mediawiki --replicas=1 -n mediawiki
deploymentconfig.apps.openshift.io/mediawiki scaled


```

Looking at the MigPlan again after scaling the replicas back up
```

$ oc get migplan mediawiki01 -o yaml -n mig
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  annotations:
    touch: 2e5cd978-9c6f-4a33-89a7-0a459cc088a1
  creationTimestamp: "2019-08-04T15:01:53Z"
  generation: 16
  name: mediawiki01
  namespace: mig
  resourceVersion: "2051373"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migplans/mediawiki01
  uid: cb77fd08-b6c8-11e9-8be2-0214de412234
spec:
  destMigClusterRef:
    name: host
    namespace: mig
  migStorageRef:
    name: jwms3
    namespace: mig
  namespaces:
  - mediawiki
  persistentVolumes:
  - capacity: 10Gi
    name: vol195
    pvc:
      accessModes:
      - ReadWriteOnce
      name: mediawiki
      namespace: mediawiki
    selection:
      storageClass: gp2
    supported:
      actions:
      - copy
      - move
  - capacity: 10Gi
    name: vol53
    pvc:
      accessModes:
      - ReadWriteOnce
      name: mariadb
      namespace: mediawiki
    selection:
      storageClass: gp2
    supported:
      actions:
      - copy
      - move
  srcMigClusterRef:
    name: jwm0729ocp3a
    namespace: mig
status:
  conditions:
  - category: Required
    lastTransitionTime: "2019-08-04T15:02:06Z"
    message: The `persistentVolumes` list has been updated with discovered PVs.
    reason: Done
    status: "True"
    type: PvsDiscovered
  - category: Required
    lastTransitionTime: "2019-08-04T15:02:06Z"
    message: The storage resources have been created.
    status: "True"
    type: StorageEnsured
  - category: Required
    lastTransitionTime: "2019-08-04T15:02:07Z"
    message: The migration registry resources have been created.
    status: "True"
    type: RegistriesEnsured
  - category: Error
    lastTransitionTime: "2019-08-04T15:22:16Z"
    message: PV in `persistentVolumes` [vol195,vol53] has an unsupported `action`.
    reason: NotDone
    status: "True"
    type: PvInvalidAction

```

<img width="1609" alt="Screen Shot 2019-08-04 at 11 22 45 AM" src="https://user-images.githubusercontent.com/206875/62425736-809d5180-b6aa-11e9-90ba-9912573129f0.png">

**Comment by eriknelson** [comment] 2019-08-05 11:31
I'm remembering this now. I had some conversations with Jeff about this; basically after the app is migrated, the controller "rediscovers" the PVs, and of source since the app has been shut down, there are no PVs in use, so the PVs are removed from the plan, hence 0 (that table field is read from the MigPlan's list of PVs).

I suspect this will actually be fixed when @ibolton336 implements plan closure on final delete. The controller will stop reconciling the plan, so it will remain at the correct count.

**Comment by jortel** [comment] 2019-08-06 15:02
After a reading this issue, I have a better understanding of the impact on the user.  Closing the plan won't really resolve this issue. All of the reconcile events generated by remote watch of velero (and lots of other) resources will cause the plan controller to constantly run pv discovery during the migration.  By the time the migration has finished and before the UI closes the plan , the pv list well be empty.

I think there is a strong case to be made for disabling _discovery_ and _ensure_ parts the plan reconcile while a migration is `Running`. As I mentioned, all of the remote watch events related to velero (and other resources) are propagated through the plan which triggers a lot of plan reconciles. The _discovery_ and _ensure_ parts of the reconcile are relatively expensive and mutate the plan while migrations are in progress which seems undesirable. The _full_ reconcile would be re-enabled after the `Competed` migration has failed or a _stage_ migration succeeds. So after a successful _final_ migration, it would not be re-enabled.  This should preserve the PV list.

**Comment by eriknelson** [comment] 2019-08-14 17:00
Confirmed @jortel's work has resolved this in the UI. Thank you Jeff!

**Closed by eriknelson** 2019-08-14 17:00 UTC
Labels: beta-blocker, bug
