### ISSUE TITLE
Status for 'Migration Successful' displayed on a MigPlan in bad state and no Stage or Migrates ever run

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-ui#328] opened 2019-07-11 16:39 UTC
I created an intentional bad migration, didn't select any namespaces.
I never ran a Stage or Migrate, but status is saying it was successful

<img width="1361" alt="Screen Shot 2019-07-11 at 12 38 33 PM" src="https://user-images.githubusercontent.com/206875/61068781-d139cb80-a3d8-11e9-86f1-2720ab9884ef.png">

```
$ oc get migplan bad1 -o yaml
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  annotations:
    touch: d83a00f1-e2ce-4b49-b34c-f0d2bfdfdd59
  creationTimestamp: "2019-07-11T16:24:48Z"
  generation: 2
  name: bad1
  namespace: mig
  resourceVersion: "447392"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migplans/bad1
  uid: 66b4e6e9-a3f8-11e9-9a19-0ac4ab43e1ee
spec:
  destMigClusterRef:
    name: host
    namespace: mig
  migStorageRef:
    name: my-s2-bucket
    namespace: mig
  srcMigClusterRef:
    name: ocp3
    namespace: mig
status:
  conditions:
  - category: Critical
    lastTransitionTime: "2019-07-11T16:24:48Z"
    message: The `migStorageRef` must reference a `migstorage`.
    reason: NotFound
    status: "True"
    type: InvalidStorageRef
  - category: Critical
    lastTransitionTime: "2019-07-11T16:24:48Z"
    message: The `namespaces` list may not be empty.
    status: "True"
    type: NamespaceListEmpty
```

**Comment by jwmatthews** [comment] 2019-07-11 20:23
To recreate
 creat multiple MigPlans, all of them using the same Source Cluster + Namespace

Maybe their is an issue with how we associate 
MigPlan - MigMigrations

**Comment by eriknelson** [comment] 2019-07-17 15:03
It's possible @Danil-Grigorev fixed this with his recent PR, if you could retest.

**Comment by eriknelson** [comment] 2019-07-17 17:15
I can confirm this issue has been fixed and displays "Not Ready". Additionally, this plan will not validate during the validation stage, which we have implemented since this was originally filed. Closing.

**Closed by eriknelson** 2019-07-17 17:15 UTC
Labels: beta-blocker
